openapi: 3.0.4
info:
  title: Country Lookup
  description: Country Lookup is a simple tool for looking up country data. It returns the country name, capital, and more.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/countrylookup:
    get:
      summary: Lookup Country
      description: Country Lookup is a simple tool for looking up country data. It returns the country name, capital, and more.
      operationId: countrylookup
      parameters:
      - name: country
        in: query
        schema:
          type: string
        required: true
        description: The Country name or ISO code of the country for which you want to get the data (e.g., USA)
        example: USA
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  search: USA
                  countries:
                  - name:
                      common: United States
                      official: United States of America
                      native:
                        eng:
                          official: United States of America
                          common: United States
                    tld:
                    - .us
                    cca2: US
                    ccn3: '840'
                    cca3: USA
                    cioc: USA
                    independent: true
                    status: officially-assigned
                    currencies:
                      USD:
                        name: United States dollar
                        symbol: $
                    capital:
                    - Washington D.C.
                    altSpellings:
                    - US
                    - USA
                    - United States of America
                    region: Americas
                    subregion: North America
                    languages:
                      eng: English
                    latlng:
                    - 38
                    - -97
                    landlocked: false
                    borders:
                    - CAN
                    - MEX
                    area: 9372610
                    flag: "\U0001F1FA\U0001F1F8"
                    majorCities:
                    - Akron
                    - Albany
                    - Albuquerque
                    - Alexandria
                    - Allentown
                    - Alpharetta
                    - Anaheim
                    - Anchorage
                    - Ann Arbor
                    - Arlington
                    - Arlington
                    - Asheville
                    - Astoria
                    - Atlanta
                    - Aurora
                    - Austin
                    - Bakersfield
                    - Baltimore
                    - Baton Rouge
                    - Beaverton
                    - Bellevue
                    - Berkeley
                    - Beverly Hills
                    - Birmingham
                    - Boca Raton
                    - Boise
                    - Boston
                    - Boulder
                    - Bronx
                    - Brooklyn
                    - Buffalo
                    - Cambridge
                    - Carlsbad
                    - Cary
                    - Chandler
                    - Charleston
                    - Charlotte
                    - Charlottesville
                    - Chattanooga
                    - Cherry Hill
                    - Chicago
                    - Cincinnati
                    - Clearwater
                    - Cleveland
                    - Colorado Springs
                    - Columbia
                    - Columbia
                    - Columbus
                    - Costa Mesa
                    - Dallas
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
