openapi: 3.0.4
info:
  title: Country Lookup
  description: >-
    Country Lookup is a simple tool for looking up country data. It returns the
    country name, capital, and more.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/countrylookup:
    get:
      summary: Lookup Country
      description: Lookup country data based on the country ISO Code
      operationId: countrylookup
      parameters:
        - name: country
          in: query
          schema:
            type: string
          required: true
          description: >-
            The Country name or ISO code of the country for which you want to
            get the data (e.g., USA)
          example: USA
        - name: majorcities
          in: query
          schema:
            type: boolean
          required: false
          description: >-
            Specify if you would like to return all major cities of the country
            found
          example: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  search: USA
                  countries:
                    - name:
                        common: United States
                        official: United States of America
                        native:
                          eng:
                            official: United States of America
                            common: United States
                      tld:
                        - .us
                      cca2: US
                      ccn3: '840'
                      cca3: USA
                      cioc: USA
                      independent: true
                      status: officially-assigned
                      capital:
                        - Washington D.C.
                      altSpellings:
                        - US
                        - USA
                        - United States of America
                      region: Americas
                      subregion: North America
                      languages:
                        eng: English
                      latlng:
                        - 38
                        - -97
                      landlocked: false
                      flag: ðŸ‡ºðŸ‡¸
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
