name: apiverve_countrylookup
description: Country Lookup is a simple tool for looking up country data. It returns the country name, capital, and more.
version: 1.1.14
homepage: https://apiverve.com/marketplace/countrylookup?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/countrylookup-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
